<a href="https://colab.research.google.com/github/Aurora-DS-1728821/AuroraDS-AnalyticsEngineering/blob/main/Simple_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create Database

In [ ]:
import sqlite3
import pandas as pd

# Create or connect to a database file
conn = sqlite3.connect("shop.db")
cur = conn.cursor()

print("Database connected successfully.")

Database connected successfully.

Create simple Table

In [ ]:
cur.execute("""
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name TEXT,
    category TEXT,
    price REAL,
    quantity INTEGER
);
""")

conn.commit()
print("Table created.")

Table created.

Insert sample data

In [ ]:
cur.executemany("""
INSERT INTO sales (product_name, category, price, quantity)
VALUES (?, ?, ?, ?);
""", [
    ('Laptop', 'Electronics', 800, 2),
    ('Phone', 'Electronics', 500, 3),
    ('Headphones', 'Electronics', 100, 5),
    ('Desk Chair', 'Furniture', 150, 4),
    ('Desk', 'Furniture', 300, 2),
    ('Notebook', 'Stationery', 5, 20),
    ('Pen Pack', 'Stationery', 10, 10)
])

conn.commit()
print("Data inserted.")

Data inserted.

View all data

In [ ]:
df = pd.read_sql_query("SELECT * FROM sales ", conn)
df

   sale_id product_name     category  price  quantity
0        1       Laptop  Electronics  800.0         2
1        2        Phone  Electronics  500.0         3
2        3   Headphones  Electronics  100.0         5
3        4   Desk Chair    Furniture  150.0         4
4        5         Desk    Furniture  300.0         2
5        6     Notebook   Stationery    5.0        20
6        7     Pen Pack   Stationery   10.0        10

Calculate the AVG Price

In [ ]:
pd.read_sql_query("SELECT AVG(price) FROM sales", conn)

   AVG(price)
0  266.428571

Calculate Total Quantity Sold

In [ ]:
pd.read_sql_query("SELECT SUM(quantity) FROM sales", conn)

   SUM(quantity)
0             46

Calculate Highest and Lowest Price

In [ ]:
pd.read_sql_query("SELECT MAX(price), MIN(price) FROM sales", conn)

   MAX(price)  MIN(price)
0       800.0         5.0

Calculate revenue per product

In [ ]:
pd.read_sql_query("SELECT price * quantity AS revenue, product_name FROM sales GROUP BY product_name", conn)

   revenue product_name
0    600.0         Desk
1    600.0   Desk Chair
2    500.0   Headphones
3   1600.0       Laptop
4    100.0     Notebook
5    100.0     Pen Pack
6   1500.0        Phone

Calculate total revenue

In [ ]:
pd.read_sql_query("SELECT SUM(revenue) FROM sales", conn)

   SUM(revenue)
0        5000.0

Calculate revenue per category

In [ ]:
pd.read_sql_query("SELECT SUM(price*quantity), category FROM sales GROUP BY category", conn)

   SUM(price*quantity)     category
0               3600.0  Electronics
1               1200.0    Furniture
2                200.0   Stationery

Calculate average price per category

In [ ]:
pd.read_sql_query("SELECT AVG(price) FROM sales GROUP BY category",conn)

   AVG(price)
0  466.666667
1  225.000000
2    7.500000

Calculate count products per category

In [ ]:
pd.read_sql_query("SELECT COUNT(product_name) FROM SALES GROUP BY category", conn)

   COUNT(product_name)
0                    3
1                    2
2                    2

Which category has a revenue greater than 2000

In [ ]:
pd.read_sql_query("SELECT SUM(price*quantity), category FROM sales GROUP BY category HAVING SUM(price*quantity)>2000", conn)

   SUM(price*quantity)     category
0               3600.0  Electronics